name: Build LaTeX Resume

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex

      - name: Rename output PDF
        run: mv resume.pdf "Ankush Kapoor resume.pdf"

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: "Ankush Kapoor resume.pdf"
