name: Build and Upload LaTeX Resume

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex

      - name: Rename PDF
        run: mv resume.pdf "Ankush Kapoor resume.pdf"

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-artifact
          path: "Ankush Kapoor resume.pdf"

      - name: Commit and push PDF to pdf/ folder
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          mkdir -p pdf
          rm -f pdf/*.pdf
          mv "Ankush Kapoor resume.pdf" pdf/

          git add pdf/

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update resume PDF"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
